name: Cypress Tests with Reporting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: Cypress tests
    strategy:
      matrix:
        device: ['desktop', 'iphone13', 'galaxyS21']
    env:
      CYPRESS_defaultDevice: ${{ matrix.device }}
      CYPRESS_deviceProfile: ${{ matrix.device }}
      CYPRESS_testType: ${{ contains(matrix.device, 'desktop') && 'web' || 'mobile' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Actualizado a v4

      - name: Install Node.js
        uses: actions/setup-node@v4  # Actualizado a v4
        with:
          node-version: 20  # Versión LTS actual
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6  # Actualizado a v6
        with:
          browser: chrome
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
          config-file: cypress.config.js
        env:
          CI: true

      - name: Generate HTML report
        if: always()
        run: |
          npx mochawesome-merge "cypress/reports/mochawesome/*.json" > cypress/reports/mochawesome/combined.json
          npx marge cypress/reports/mochawesome/combined.json -o cypress/reports/mochawesome/html --reportTitle "Cypress Test Report - ${{ matrix.device }}"

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4  # Actualizado a v4
        with:
          name: cypress-report-${{ matrix.device }}
          path: cypress/reports/mochawesome/html
          retention-days: 7

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4  # Actualizado a v4
        with:
          name: cypress-screenshots-${{ matrix.device }}
          path: cypress/screenshots
          retention-days: 3

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4  # Actualizado a v4
        with:
          name: cypress-videos-${{ matrix.device }}
          path: cypress/videos
          retention-days: 3