name: Cypress Tests with Allure Reporting (Desktop Only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: Cypress tests (Desktop)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Clean npm cache and remove node_modules
        run: |
          npm cache clean --force
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install dependencies (with fresh lock file)
        run: npm install

      - name: Install Java (for Allure)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: npm run test
          start: npm start
          wait-on: 'http://localhost:3000'
          config-file: cypress.config.js
        env:
          CI: true
          CYPRESS_deviceProfile: 'desktop'
          CYPRESS_testType: 'web'

      # Resto de los pasos permanecen igual...
      - name: Generate Allure report
        if: always()
        run: npm run allure:generate