name: Cypress Tests with Allure Reporting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: Cypress tests
    strategy:
      matrix:
        device: ['desktop', 'iphone13', 'galaxyS21']
    env:
      CYPRESS_defaultDevice: ${{ matrix.device }}
      CYPRESS_deviceProfile: ${{ matrix.device }}
      CYPRESS_testType: ${{ contains(matrix.device, 'desktop') && 'web' || 'mobile' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Java (for Allure)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: npm run test
          start: npm start
          wait-on: 'http://localhost:3000'
          config-file: cypress.config.js
        env:
          CI: true

      - name: Generate Allure report
        if: always()
        run: |
          npm install allure-commandline
          npm run allure:generate

      - name: Upload Allure report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.device }}
          path: allure-report
          retention-days: 7

      - name: Archive Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.device }}
          path: allure-results
          retention-days: 7

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{ matrix.device }}
          path: cypress/screenshots
          retention-days: 3

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ matrix.device }}
          path: cypress/videos
          retention-days: 3

      - name: Publish Allure Report
        if: always()
        uses: actions/upload-pages-artifact@v2
        with:
          path: allure-report